version: '3.8'

services:
  # SarvanOM Backend - FastAPI Application (Development)
  sarvanom_backend:
    build:
      context: .
      dockerfile: Dockerfile.enterprise
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - ./:/app
      - /app/__pycache__
      - /app/.pytest_cache
    depends_on:
      postgres:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - sarvanom-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/basic"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend - React/Next.js Application (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://sarvanom_backend:8000
      - VITE_API_BASE_URL=http://sarvanom_backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      sarvanom_backend:
        condition: service_healthy
    networks:
      - sarvanom-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  sarvanom-network:
    external: true
