version: '3.8'

services:
  # PostgreSQL - Essential Database (Lightweight)
  postgres:
    image: postgres:15-alpine
    container_name: sarvanom-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sarvanom_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - sarvanom-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sarvanom_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Qdrant - Essential Vector Database (Lightweight)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: sarvanom-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - sarvanom-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Meilisearch - Essential Search Engine (Lightweight)
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: sarvanom-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=development
    volumes:
      - ./data/meilisearch:/meili_data
    networks:
      - sarvanom-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  sarvanom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 