version: '3.8'

services:
  # Meilisearch - Zero-budget Elasticsearch alternative
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: sarvanom-meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=your-master-key-here  # Optional: for production
    volumes:
      - meilisearch_data:/meili_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - knowledge-hub-network

  # Optional: Meilisearch Admin UI
  meilisearch-admin:
    image: getmeili/meilisearch:latest
    container_name: sarvanom-meilisearch-admin
    ports:
      - "7701:7700"
    environment:
      - MEILI_MASTER_KEY=your-master-key-here
    command: ["meilisearch", "--http-addr", "0.0.0.0:7700", "--env", "development"]
    restart: unless-stopped
    networks:
      - knowledge-hub-network

volumes:
  meilisearch_data:
    driver: local

networks:
  knowledge-hub-network:
    driver: bridge 