global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # SarvanOM Backend
  - job_name: 'sarvanom-backend'
    static_configs:
      - targets: ['backend-test:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # ArangoDB
  - job_name: 'arangodb'
    static_configs:
      - targets: ['arangodb:8529']

  # Qdrant
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']

  # Meilisearch
  - job_name: 'meilisearch'
    static_configs:
      - targets: ['meilisearch:7700']

  # Ollama
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']

  # MinIO
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
