"""
Models package for API Gateway.

This package contains all request and response models used by the API gateway.
"""

from .requests import (
    LoginRequest,
    RegisterRequest,
    QueryRequest,
    ComprehensiveQueryRequest,
    FeedbackRequest,
    ExpertReviewRequest,
    TaskGenerationRequest,
    AgentRequest,
    BrowserSearchRequest,
    PDFProcessRequest,
    CodeExecutorRequest,
    KnowledgeGraphRequest,
    DatabaseQueryRequest,
    WebCrawlerRequest,
    QueryUpdateRequest,
    GenericRequest,
)

from .responses import (
    AuthResponse,
    APIKeyResponse,
    QueryResponse,
    ComprehensiveQueryResponse,
    FeedbackResponse,
    ExpertReviewResponse,
    QueryListResponse,
    QueryDetailResponse,
    QueryStatusResponse,
    HealthResponse,
    MetricsResponse,
    SystemDiagnosticsResponse,
    AnalyticsResponse,
    SecurityStatusResponse,
    IntegrationStatusResponse,
    AgentResponse,
    WebSocketMessage,
    ErrorResponse,
    GenericResponse,
)

from .websocket import (
    MessageType,
    ConnectionStatus,
    WebSocketConnection,
    WebSocketMessage as WSMessage,
    QueryUpdateMessage,
    CollaborationMessage,
    SystemNotificationMessage,
    UserActivityMessage,
    TypingIndicatorMessage,
    WebSocketError,
    WebSocketEvent,
    WebSocketSubscription,
    WebSocketMetrics,
    WebSocketConfig,
)

__all__ = [
    # Request models
    "LoginRequest",
    "RegisterRequest",
    "QueryRequest",
    "ComprehensiveQueryRequest",
    "FeedbackRequest",
    "ExpertReviewRequest",
    "TaskGenerationRequest",
    "AgentRequest",
    "BrowserSearchRequest",
    "PDFProcessRequest",
    "CodeExecutorRequest",
    "KnowledgeGraphRequest",
    "DatabaseQueryRequest",
    "WebCrawlerRequest",
    "QueryUpdateRequest",
    "GenericRequest",
    # Response models
    "AuthResponse",
    "APIKeyResponse",
    "QueryResponse",
    "ComprehensiveQueryResponse",
    "FeedbackResponse",
    "ExpertReviewResponse",
    "QueryListResponse",
    "QueryDetailResponse",
    "QueryStatusResponse",
    "HealthResponse",
    "MetricsResponse",
    "SystemDiagnosticsResponse",
    "AnalyticsResponse",
    "SecurityStatusResponse",
    "IntegrationStatusResponse",
    "AgentResponse",
    "WebSocketMessage",
    "ErrorResponse",
    "GenericResponse",
    # WebSocket models
    "MessageType",
    "ConnectionStatus",
    "WebSocketConnection",
    "WSMessage",
    "QueryUpdateMessage",
    "CollaborationMessage",
    "SystemNotificationMessage",
    "UserActivityMessage",
    "TypingIndicatorMessage",
    "WebSocketError",
    "WebSocketEvent",
    "WebSocketSubscription",
    "WebSocketMetrics",
    "WebSocketConfig",
]
