# Staging Environment Configuration  
# This file contains staging-specific settings for the SarvanOM platform
# Production-like environment for final testing before deployment

# Core Settings
name: "staging"
debug: false
testing: false
log_level: "INFO"

# Database Configuration (MUST be set via environment variables)
# database_url: Set via DATABASE_URL environment variable
# redis_url: Set via REDIS_URL environment variable

# AI Provider Configuration (MUST be set via environment variables)
# openai_api_key: Set via OPENAI_API_KEY environment variable
# anthropic_api_key: Set via ANTHROPIC_API_KEY environment variable

# Vector Database Configuration (MUST be set via environment variables)
# vector_db_url: Set via VECTOR_DB_URL environment variable
# vector_db_api_key: Set via VECTOR_DB_API_KEY environment variable

# Search Configuration (MUST be set via environment variables)
# meilisearch_url: Set via MEILISEARCH_URL environment variable
# meilisearch_master_key: Set via MEILISEARCH_MASTER_KEY environment variable

# Knowledge Graph Configuration (MUST be set via environment variables)
# arangodb_url: Set via ARANGODB_URL environment variable
# arangodb_username: Set via ARANGODB_USERNAME environment variable
# arangodb_password: Set via ARANGODB_PASSWORD environment variable
arangodb_database: "staging_knowledge_graph"

# Security Configuration (MUST be set via environment variables)
# jwt_secret_key: Set via JWT_SECRET_KEY environment variable
cors_origins:
  - "https://staging.sarvanom.com"
  - "https://staging-api.sarvanom.com"

# Performance Settings (Staging - production-like but more permissive)
rate_limit_per_minute: 100
max_request_size_mb: 20
cache_ttl_seconds: 3600  # 1 hour
session_ttl_seconds: 7200  # 2 hours

# Feature Flags (Staging - production-like with some testing features)
backup_enabled: true
audit_log_enabled: true
security_headers_enabled: true
mock_ai_responses: false  # Use real APIs in staging
skip_authentication: false
enable_debug_endpoints: false
auto_reload: false
test_mode: false
mock_providers: false

# Agent Configuration (Staging - production-like timeouts)
agent_timeout_seconds: 45
agent_max_retries: 3
agent_backoff_factor: 2.0

# Query Configuration (Staging)
query_cache_ttl_seconds: 3600
query_max_length: 3000
query_min_confidence: 0.7

# Database Pool Settings (Staging - moderate)
db_pool_size: 10
db_max_overflow: 20
db_pool_timeout: 30

# Worker Configuration (Staging - moderate scaling)
worker_processes: 4
worker_threads: 4
max_memory_usage_mb: 2048
garbage_collection_interval: 300

# Monitoring Configuration (Staging - full monitoring)
metrics_enabled: true
metrics_port: 9090
enable_tracing: true
jaeger_agent_host: "localhost"
jaeger_agent_port: 6831
# sentry_dsn: Set via SENTRY_DSN environment variable
sentry_traces_sample_rate: 0.1
sentry_profiles_sample_rate: 0.1

# Health Check Configuration (Staging)
health_check_interval: 30
health_check_timeout: 10

# Feature Toggles (Staging - production-like feature set)
features:
  streaming: true
  batch_processing: true
  websockets: true
  graphql: false  # Disable experimental features
  admin_panel: true
  expert_review: true
  real_time_collaboration: true
  advanced_analytics: true
  multi_tenant: false
  sso: false

# Staging-specific settings
staging_data_refresh: true
staging_performance_testing: true
staging_security_scanning: true
staging_backup_retention_days: 7
staging_log_retention_days: 30